<?php
// Echhapa CMS Installation Script

function autoInstall() {
    $errors = [];
    
    try {
        // Database configuration
        $dbHost = 'localhost';
        $dbName = 'echhapa_cms';
        $dbUser = 'root';
        $dbPass = '';
        
        // Test database connection
        $pdo = new PDO("mysql:host=$dbHost;charset=utf8mb4", $dbUser, $dbPass);
        $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
        
        // Create database if it doesn't exist
        $pdo->exec("CREATE DATABASE IF NOT EXISTS `$dbName` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");
        
        // Connect to the specific database
        $pdo = new PDO("mysql:host=$dbHost;dbname=$dbName;charset=utf8mb4", $dbUser, $dbPass);
        $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
        
        // Create tables using the database schema
        require_once 'config/database.php';
        createTables($pdo);
        
        // Create admin user with specified credentials
        $adminUser = 'admin';
        $adminEmail = 'admin@echhapa.com';
        $adminPass = 'password';
        $hashedPassword = password_hash($adminPass, PASSWORD_DEFAULT);
        
        $stmt = $pdo->prepare("INSERT INTO users (username, email, password_hash, role) VALUES (?, ?, ?, 'admin')");
        $stmt->execute([$adminUser, $adminEmail, $hashedPassword]);
        $adminId = $pdo->lastInsertId();
        
        // Insert comprehensive sample data
        insertSampleData($pdo, $adminId);
        
        // Set site name
        $siteName = 'Echhapa News';
        $stmt = $pdo->prepare("INSERT INTO site_settings (setting_key, setting_value, setting_type) VALUES ('site_name', ?, 'text') ON DUPLICATE KEY UPDATE setting_value = ?");
        $stmt->execute([$siteName, $siteName]);
        
        // Create config file
        $configContent = "<?php\n";
        $configContent .= "// Database configuration - Generated by installer\n";
        $configContent .= "define('DB_HOST', '$dbHost');\n";
        $configContent .= "define('DB_NAME', '$dbName');\n";
        $configContent .= "define('DB_USER', '$dbUser');\n";
        $configContent .= "define('DB_PASS', '$dbPass');\n";
        $configContent .= "?>";
        
        if (!is_dir('config')) {
            mkdir('config', 0777, true);
        }
        file_put_contents('config/db_config.php', $configContent);
        
        // Create installed lock file
        file_put_contents('config/installed.lock', date('Y-m-d H:i:s'));
        
        // Redirect to main site
        header('Location: index.php');
        exit;
        
    } catch (Exception $e) {
        die('<h1>Installation Error</h1><p>Auto-installation failed: ' . htmlspecialchars($e->getMessage()) . '</p><p>Please check your database configuration and try again.</p>');
    }
}

// Auto-install if not already installed
if (!file_exists('config/installed.lock')) {
    // Automatic installation with predefined admin account
    autoInstall();
}

// Check if already installed (after auto-install attempt)
if (file_exists('config/installed.lock')) {
    header('Location: index.php');
    exit;
}

$step = isset($_GET['step']) ? intval($_GET['step']) : 1;
$errors = [];
$success = [];

// Handle form submissions
if ($_POST) {
    if ($step == 2) {
        // Database configuration
        $dbHost = $_POST['db_host'] ?? 'localhost';
        $dbName = $_POST['db_name'] ?? 'echhapa_cms';
        $dbUser = $_POST['db_user'] ?? 'root';
        $dbPass = $_POST['db_pass'] ?? '';
        
        try {
            // Test database connection
            $pdo = new PDO("mysql:host=$dbHost;dbname=$dbName;charset=utf8mb4", $dbUser, $dbPass);
            $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
            
            // Store database config
            $_SESSION['db_config'] = [
                'host' => $dbHost,
                'name' => $dbName,
                'user' => $dbUser,
                'pass' => $dbPass
            ];
            
            $success[] = 'Database connection successful!';
            $step = 3;
        } catch (PDOException $e) {
            $errors[] = 'Database connection failed: ' . $e->getMessage();
        }
    } elseif ($step == 3) {
        // Admin user creation
        $adminUser = $_POST['admin_user'] ?? '';
        $adminEmail = $_POST['admin_email'] ?? '';
        $adminPass = $_POST['admin_pass'] ?? '';
        $siteName = $_POST['site_name'] ?? 'Echhapa News';
        
        if (empty($adminUser) || empty($adminEmail) || empty($adminPass)) {
            $errors[] = 'All fields are required';
        } elseif (strlen($adminPass) < 6) {
            $errors[] = 'Password must be at least 6 characters';
        } else {
            try {
                session_start();
                $dbConfig = $_SESSION['db_config'];
                
                // Connect to database
                $pdo = new PDO("mysql:host={$dbConfig['host']};dbname={$dbConfig['name']};charset=utf8mb4", 
                               $dbConfig['user'], $dbConfig['pass']);
                $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
                
                // Create database first if it doesn't exist
                $pdo_base = new PDO("mysql:host={$dbConfig['host']}", $dbConfig['user'], $dbConfig['pass']);
                $pdo_base->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
                $pdo_base->exec("CREATE DATABASE IF NOT EXISTS `{$dbConfig['name']}` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");
                
                // Now reconnect to the specific database
                $pdo = new PDO("mysql:host={$dbConfig['host']};dbname={$dbConfig['name']};charset=utf8mb4", 
                               $dbConfig['user'], $dbConfig['pass']);
                $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
                
                // Create tables using the database schema
                require_once 'config/database.php';
                createTables($pdo);
                
                // Create admin user
                $hashedPassword = password_hash($adminPass, PASSWORD_DEFAULT);
                $stmt = $pdo->prepare("INSERT INTO users (username, email, password_hash, role) VALUES (?, ?, ?, 'admin')");
                $stmt->execute([$adminUser, $adminEmail, $hashedPassword]);
                $adminId = $pdo->lastInsertId();
                
                // Insert comprehensive sample data
                insertSampleData($pdo, $adminId);
                
                // Set site name
                $stmt = $pdo->prepare("INSERT INTO site_settings (setting_key, setting_value, setting_type) VALUES ('site_name', ?, 'text') ON DUPLICATE KEY UPDATE setting_value = ?");
                $stmt->execute([$siteName, $siteName]);
                
                // Create config file
                $configContent = "<?php\n";
                $configContent .= "// Database configuration - Generated by installer\n";
                $configContent .= "define('DB_HOST', '{$dbConfig['host']}');\n";
                $configContent .= "define('DB_NAME', '{$dbConfig['name']}');\n";
                $configContent .= "define('DB_USER', '{$dbConfig['user']}');\n";
                $configContent .= "define('DB_PASS', '{$dbConfig['pass']}');\n";
                $configContent .= "?>";
                
                file_put_contents('config/db_config.php', $configContent);
                
                // Create installed lock file
                file_put_contents('config/installed.lock', date('Y-m-d H:i:s'));
                
                $success[] = 'Installation completed successfully!';
                $success[] = 'Database created and populated with sample data.';
                $success[] = 'Admin account created successfully.';
                $step = 4;
            } catch (Exception $e) {
                $errors[] = 'Installation failed: ' . $e->getMessage();
            }
        }
    }
}

// Function to insert comprehensive sample data
function insertSampleData($pdo, $adminId) {
    // Insert more categories with descriptions
    $categories = [
        ['Breaking News', 'breaking-news', 'Latest breaking news and urgent updates'],
        ['World News', 'world-news', 'International news and global affairs'],
        ['Politics', 'politics', 'Political developments and government news'],
        ['Business', 'business', 'Business news, markets, and economic updates'],
        ['Technology', 'technology', 'Tech industry news and innovations'],
        ['Science', 'science', 'Scientific discoveries and research'],
        ['Sports', 'sports', 'Sports news, scores, and highlights'],
        ['Entertainment', 'entertainment', 'Entertainment and celebrity news'],
        ['Health', 'health', 'Health and medical news'],
        ['Lifestyle', 'lifestyle', 'Lifestyle, culture, and society news'],
        ['Opinion', 'opinion', 'Editorial opinions and analysis'],
        ['Weather', 'weather', 'Weather updates and forecasts']
    ];
    
    foreach ($categories as $cat) {
        $stmt = $pdo->prepare("INSERT IGNORE INTO categories (name, slug, description) VALUES (?, ?, ?)");
        $stmt->execute($cat);
    }
    
    // Insert comprehensive sample articles with realistic content
    $articles = [
        [
            'Global Economic Summit Concludes with Historic Climate Finance Agreement',
            'global-economic-summit-climate-finance',
            'World leaders reach unprecedented agreement on climate financing, committing $500 billion over the next decade to support developing nations in their transition to renewable energy.',
            '<h3>Major Breakthrough in International Climate Policy</h3>
            <p>In a landmark decision that could reshape global environmental and economic policy, delegates from 195 countries concluded the three-day Global Economic Summit with a historic climate finance agreement. The accord, officially termed the "Global Climate Transition Pact," represents the largest coordinated international investment in renewable energy infrastructure to date.</p>
            
            <h4>Key Provisions of the Agreement</h4>
            <p>The comprehensive agreement includes several groundbreaking provisions:</p>
            <ul>
            <li><strong>$500 Billion Commitment:</strong> Developed nations have pledged to contribute $500 billion over the next 10 years to support climate transition projects in developing countries.</li>
            <li><strong>Technology Transfer Initiative:</strong> A new framework for sharing renewable energy technologies and expertise across borders without traditional patent restrictions.</li>
            <li><strong>Carbon Pricing Mechanism:</strong> Implementation of a global carbon pricing system that will create financial incentives for emissions reduction.</li>
            <li><strong>Green Jobs Program:</strong> Training and employment initiatives expected to create over 50 million jobs in the renewable energy sector globally.</li>
            </ul>
            
            <h4>Implementation Timeline</h4>
            <p>The agreement will be implemented in three phases over the next decade, with the first phase beginning in January 2025. Each participating country will establish national climate transition boards to oversee fund allocation and project implementation.</p>
            
            <p>Economic analysts predict this agreement could accelerate the global transition to renewable energy by at least a decade, while also addressing economic inequality between developed and developing nations.</p>',
            1, 2
        ],
        [
            'Revolutionary AI System Achieves Breakthrough in Medical Diagnosis',
            'ai-medical-diagnosis-breakthrough',
            'New artificial intelligence system demonstrates 98% accuracy in early cancer detection, potentially revolutionizing preventive healthcare worldwide.',
            '<h3>AI Technology Surpasses Human Doctors in Diagnostic Accuracy</h3>
            <p>Researchers at the International Institute of Medical Technology have announced a major breakthrough in AI-assisted medical diagnosis. Their newly developed system, called MediCore AI, has achieved an unprecedented 98% accuracy rate in detecting early-stage cancers across multiple organ systems.</p>
            
            <h4>Comprehensive Testing Results</h4>
            <p>The AI system was tested on over 100,000 medical cases across 15 major hospitals worldwide. The results show remarkable consistency:</p>
            <ul>
            <li><strong>Lung Cancer Detection:</strong> 98.2% accuracy, identifying cases an average of 6 months earlier than traditional methods</li>
            <li><strong>Breast Cancer Screening:</strong> 97.8% accuracy with 23% fewer false positives than current mammography standards</li>
            <li><strong>Skin Cancer Analysis:</strong> 99.1% accuracy in distinguishing between benign and malignant lesions</li>
            <li><strong>Prostate Cancer Detection:</strong> 96.7% accuracy using non-invasive imaging techniques</li>
            </ul>
            
            <h4>Global Healthcare Impact</h4>
            <p>Dr. Sarah Chen, lead researcher on the project, explained the potential impact: "This technology could save millions of lives by catching cancer in its earliest, most treatable stages. We are particularly excited about its potential in underserved areas where specialist oncologists may not be readily available."</p>
            
            <p>The system is expected to be deployed in major healthcare networks starting in Q2 2025, pending regulatory approval from health authorities worldwide.</p>',
            5, 1
        ],
        [
            'Space Tourism Reaches New Milestone with First Commercial Moon Landing',
            'commercial-moon-landing-space-tourism',
            'Private aerospace company successfully lands civilian passengers on lunar surface, marking the beginning of a new era in space tourism.',
            '<h3>Historic Achievement Opens Moon to Civilian Exploration</h3>
            <p>Yesterday marked a pivotal moment in space exploration history as Stellar Dynamics Corporation successfully completed the first commercial moon landing mission, carrying four civilian passengers to the lunar surface. The mission, designated Luna-Tourist-1, represents a quantum leap forward in making space accessible to private citizens.</p>
            
            <h4>Mission Details and Achievements</h4>
            <p>The carefully planned mission achieved several significant milestones:</p>
            <ul>
            <li><strong>Safe Landing:</strong> The spacecraft touched down in the Sea of Tranquility, just 2 kilometers from the historic Apollo 11 landing site</li>
            <li><strong>Extended Stay:</strong> Passengers spent 72 hours on the lunar surface, conducting experiments and exploration activities</li>
            <li><strong>Scientific Research:</strong> The crew collected over 50 kilograms of lunar samples for research institutions on Earth</li>
            <li><strong>Technology Demonstration:</strong> Successfully tested new life support systems designed for extended lunar habitation</li>
            </ul>
            
            <h4>The Passengers</h4>
            <p>The four civilian astronauts included Dr. Maria Rodriguez, a marine biologist studying extremophiles; James Park, a technology entrepreneur; Lisa Thompson, an artist documenting the experience; and Ahmed Hassan, a retired engineer and space enthusiast.</p>
            
            <p>"Standing on the Moon and looking back at Earth was the most profound experience of my life," said Dr. Rodriguez during the live broadcast from the lunar surface. "It puts everything into perspective about our place in the universe."</p>
            
            <h4>Future of Space Tourism</h4>
            <p>This successful mission paves the way for regular civilian lunar tourism, with Stellar Dynamics planning monthly flights starting in 2026. The company has already received over 1,000 applications for future lunar missions, despite the $2.5 million per-person cost.</p>',
            5, 3
        ],
        [
            'Global Food Security Initiative Launches Vertical Farming Revolution',
            'vertical-farming-food-security-initiative',
            'International coalition unveils massive vertical farming project aimed at producing 40% more food while using 95% less water and land.',
            '<h3>Innovative Agriculture Technology Addresses Growing Food Crisis</h3>
            <p>An ambitious international initiative was unveiled today that promises to revolutionize global food production through advanced vertical farming technologies. The Global Food Security Coalition, comprising 45 nations, announced a $200 billion investment in vertical farming infrastructure designed to address the growing global food crisis.</p>
            
            <h4>Technological Innovation</h4>
            <p>The initiative centers around breakthrough developments in agricultural technology:</p>
            <ul>
            <li><strong>AI-Controlled Growing Systems:</strong> Advanced algorithms optimize lighting, nutrients, and environmental conditions for maximum yield</li>
            <li><strong>Closed-Loop Water Systems:</strong> Innovative recycling technology reduces water usage by 95% compared to traditional farming</li>
            <li><strong>Genetic Optimization:</strong> Specially developed crop varieties thrive in controlled vertical environments</li>
            <li><strong>Renewable Energy Integration:</strong> Solar and wind power systems provide sustainable energy for operations</li>
            </ul>
            
            <h4>Global Implementation Plan</h4>
            <p>The project will be implemented in three phases over seven years:</p>
            <p><strong>Phase 1 (2025-2026):</strong> Construction of 500 pilot facilities in urban areas across 20 countries, focusing on leafy greens and herbs.</p>
            <p><strong>Phase 2 (2027-2029):</strong> Expansion to 2,000 facilities with capabilities for root vegetables, fruits, and protein alternatives.</p>
            <p><strong>Phase 3 (2030-2032):</strong> Full-scale deployment of 10,000 facilities worldwide, targeting production of staple grains and comprehensive nutrition solutions.</p>
            
            <h4>Environmental and Social Impact</h4>
            <p>Dr. Elena Petrov, Director of the Global Food Security Coalition, emphasized the environmental benefits: "This initiative will reduce agricultural land use by 60% while producing 40% more food. We are also creating sustainable employment opportunities in urban areas where traditional farming isnt viable."</p>
            
            <p>The project is expected to create over 5 million jobs globally and significantly reduce food transportation costs and carbon emissions.</p>',
            9, 4
        ],
        [
            'Breakthrough in Quantum Computing Promises to Transform Cybersecurity',
            'quantum-computing-cybersecurity-breakthrough',
            'Scientists achieve stable quantum encryption that could make current hacking methods obsolete while revolutionizing secure communications.',
            '<h3>Quantum Encryption Reaches Commercial Viability</h3>
            <p>Researchers at the Quantum Technology Institute have achieved a major breakthrough in quantum computing that promises to revolutionize cybersecurity. Their new quantum encryption protocol, dubbed QuantumShield, has demonstrated the ability to create virtually unbreakable secure communications channels.</p>
            
            <h4>Revolutionary Security Technology</h4>
            <p>The breakthrough addresses several critical challenges in quantum computing and cybersecurity:</p>
            <ul>
            <li><strong>Stable Quantum States:</strong> New error correction methods maintain quantum coherence for over 1 hour, a 1000x improvement</li>
            <li><strong>Instantaneous Detection:</strong> Any attempt to intercept quantum-encrypted communications is immediately detected and reported</li>
            <li><strong>Scalable Implementation:</strong> The technology can be integrated into existing internet infrastructure with minimal modification</li>
            <li><strong>Cost-Effective Production:</strong> Manufacturing costs have been reduced by 90% through innovative design approaches</li>
            </ul>
            
            <h4>Impact on Current Cybersecurity</h4>
            <p>The implications for cybersecurity are profound. Current encryption methods that would take classical computers millions of years to break could be rendered obsolete, but QuantumShield provides protection even against quantum computer attacks.</p>
            
            <p>"We are essentially future-proofing digital security," explained Dr. Robert Kim, lead researcher on the project. "Even as quantum computers become more powerful, this encryption method will remain secure because it leverages the fundamental properties of quantum mechanics."</p>
            
            <h4>Commercial Applications</h4>
            <p>Major technology companies have already expressed interest in implementing the technology:</p>
            <ul>
            <li><strong>Financial Services:</strong> Banks and payment processors are testing quantum-secured transaction systems</li>
            <li><strong>Healthcare:</strong> Medical institutions plan to use the technology to protect patient data</li>
            <li><strong>Government Communications:</strong> Several nations are developing quantum-secured diplomatic communication networks</li>
            <li><strong>Critical Infrastructure:</strong> Power grids and transportation systems will benefit from quantum-protected control systems</li>
            </ul>
            
            <p>The first commercial quantum encryption services are expected to launch in late 2025, with widespread adoption anticipated by 2027.</p>',
            5, 5
        ]
    ];
    
    foreach ($articles as $index => $article) {
        $stmt = $pdo->prepare("INSERT IGNORE INTO articles (title, slug, excerpt, content, category_id, author_id, status, published_at, views) VALUES (?, ?, ?, ?, ?, ?, 'published', NOW(), ?)");
        $stmt->execute([$article[0], $article[1], $article[2], $article[3], $article[4], $adminId, rand(150, 2500)]);
    }
}

if ($step == 1) {
    session_start();
}
?>
<!DOCTYPE html>
<html lang="en" data-bs-theme="dark">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Echhapa CMS Installation</title>
    <link href="https://cdn.replit.com/agent/bootstrap-agent-dark-theme.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" rel="stylesheet">
</head>
<body class="bg-dark">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8 col-lg-6">
                <div class="card mt-5 shadow">
                    <div class="card-header text-center py-4">
                        <h2 class="fw-bold mb-0">Echhapa CMS</h2>
                        <p class="text-muted mb-0">Installation Wizard</p>
                    </div>
                    <div class="card-body p-5">
                        <!-- Progress Bar -->
                        <div class="progress mb-4">
                            <div class="progress-bar" style="width: <?php echo ($step / 4) * 100; ?>%"></div>
                        </div>
                        
                        <?php foreach ($errors as $error): ?>
                        <div class="alert alert-danger">
                            <i class="fas fa-exclamation-triangle me-2"></i><?php echo htmlspecialchars($error); ?>
                        </div>
                        <?php endforeach; ?>
                        
                        <?php foreach ($success as $message): ?>
                        <div class="alert alert-success">
                            <i class="fas fa-check-circle me-2"></i><?php echo htmlspecialchars($message); ?>
                        </div>
                        <?php endforeach; ?>
                        
                        <?php if ($step == 1): ?>
                        <!-- Step 1: Welcome -->
                        <div class="text-center mb-4">
                            <i class="fas fa-rocket fa-3x text-primary mb-3"></i>
                            <h4>Welcome to Echhapa CMS</h4>
                            <p class="text-muted">This installer will help you set up your news portal in just a few steps.</p>
                        </div>
                        
                        <div class="mb-4">
                            <h6>System Requirements Check:</h6>
                            <ul class="list-group">
                                <li class="list-group-item d-flex justify-content-between">
                                    PHP Version (>= 7.4)
                                    <?php if (version_compare(PHP_VERSION, '7.4.0', '>=')): ?>
                                    <span class="text-success"><i class="fas fa-check"></i> <?php echo PHP_VERSION; ?></span>
                                    <?php else: ?>
                                    <span class="text-danger"><i class="fas fa-times"></i> <?php echo PHP_VERSION; ?></span>
                                    <?php endif; ?>
                                </li>
                                <li class="list-group-item d-flex justify-content-between">
                                    PDO Extension
                                    <?php if (extension_loaded('pdo')): ?>
                                    <span class="text-success"><i class="fas fa-check"></i> Enabled</span>
                                    <?php else: ?>
                                    <span class="text-danger"><i class="fas fa-times"></i> Not Found</span>
                                    <?php endif; ?>
                                </li>
                                <li class="list-group-item d-flex justify-content-between">
                                    MySQL Extension
                                    <?php if (extension_loaded('pdo_mysql')): ?>
                                    <span class="text-success"><i class="fas fa-check"></i> Enabled</span>
                                    <?php else: ?>
                                    <span class="text-danger"><i class="fas fa-times"></i> Not Found</span>
                                    <?php endif; ?>
                                </li>
                                <li class="list-group-item d-flex justify-content-between">
                                    Uploads Directory
                                    <?php if (is_writable('uploads') || mkdir('uploads', 0777, true)): ?>
                                    <span class="text-success"><i class="fas fa-check"></i> Writable</span>
                                    <?php else: ?>
                                    <span class="text-danger"><i class="fas fa-times"></i> Not Writable</span>
                                    <?php endif; ?>
                                </li>
                            </ul>
                        </div>
                        
                        <div class="d-grid">
                            <a href="?step=2" class="btn btn-primary btn-lg">
                                <i class="fas fa-arrow-right me-2"></i>Continue to Database Setup
                            </a>
                        </div>
                        
                        <?php elseif ($step == 2): ?>
                        <!-- Step 2: Database Configuration -->
                        <div class="text-center mb-4">
                            <i class="fas fa-database fa-3x text-primary mb-3"></i>
                            <h4>Database Configuration</h4>
                            <p class="text-muted">Please provide your database connection details.</p>
                        </div>
                        
                        <form method="POST">
                            <div class="mb-3">
                                <label class="form-label">Database Host</label>
                                <input type="text" class="form-control" name="db_host" value="localhost" required>
                            </div>
                            
                            <div class="mb-3">
                                <label class="form-label">Database Name</label>
                                <input type="text" class="form-control" name="db_name" value="echhapa_cms" required>
                            </div>
                            
                            <div class="mb-3">
                                <label class="form-label">Database Username</label>
                                <input type="text" class="form-control" name="db_user" value="root" required>
                            </div>
                            
                            <div class="mb-3">
                                <label class="form-label">Database Password</label>
                                <input type="password" class="form-control" name="db_pass">
                            </div>
                            
                            <div class="d-grid gap-2">
                                <button type="submit" class="btn btn-primary">
                                    <i class="fas fa-check me-2"></i>Test Database Connection
                                </button>
                                <a href="?step=1" class="btn btn-outline-secondary">
                                    <i class="fas fa-arrow-left me-2"></i>Back
                                </a>
                            </div>
                        </form>
                        
                        <?php elseif ($step == 3): ?>
                        <!-- Step 3: Admin User Creation -->
                        <div class="text-center mb-4">
                            <i class="fas fa-user-shield fa-3x text-primary mb-3"></i>
                            <h4>Admin Account Setup</h4>
                            <p class="text-muted">Create your administrator account and configure basic site settings.</p>
                        </div>
                        
                        <form method="POST">
                            <div class="mb-3">
                                <label class="form-label">Site Name</label>
                                <input type="text" class="form-control" name="site_name" value="Echhapa News" required>
                            </div>
                            
                            <hr>
                            
                            <div class="mb-3">
                                <label class="form-label">Admin Username</label>
                                <input type="text" class="form-control" name="admin_user" required>
                            </div>
                            
                            <div class="mb-3">
                                <label class="form-label">Admin Email</label>
                                <input type="email" class="form-control" name="admin_email" required>
                            </div>
                            
                            <div class="mb-3">
                                <label class="form-label">Admin Password</label>
                                <input type="password" class="form-control" name="admin_pass" required minlength="6">
                                <div class="form-text">Minimum 6 characters required.</div>
                            </div>
                            
                            <div class="d-grid gap-2">
                                <button type="submit" class="btn btn-success">
                                    <i class="fas fa-rocket me-2"></i>Complete Installation
                                </button>
                                <a href="?step=2" class="btn btn-outline-secondary">
                                    <i class="fas fa-arrow-left me-2"></i>Back
                                </a>
                            </div>
                        </form>
                        
                        <?php elseif ($step == 4): ?>
                        <!-- Step 4: Installation Complete -->
                        <div class="text-center">
                            <i class="fas fa-check-circle fa-4x text-success mb-4"></i>
                            <h4 class="text-success mb-3">Installation Complete!</h4>
                            <p class="text-muted mb-4">Echhapa CMS has been successfully installed and configured.</p>
                            
                            <div class="alert alert-warning">
                                <i class="fas fa-exclamation-triangle me-2"></i>
                                <strong>Important:</strong> For security reasons, please delete this installation file (install.php) from your server.
                            </div>
                            
                            <div class="d-grid gap-2">
                                <a href="/admin/" class="btn btn-primary btn-lg">
                                    <i class="fas fa-tachometer-alt me-2"></i>Go to Admin Dashboard
                                </a>
                                <a href="/" class="btn btn-outline-secondary">
                                    <i class="fas fa-eye me-2"></i>View Website
                                </a>
                            </div>
                        </div>
                        <?php endif; ?>
                        
                    </div>
                    <div class="card-footer text-center text-muted">
                        <small>Echhapa CMS v1.0 - Powered by PHP & MySQL</small>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>
